using System.Text.Json.Serialization;

namespace Poc.Contracts;

/// <summary>
/// Business payload carried end-to-end through the pipeline. Shared by the original
/// request and the final enriched command so the join can copy it verbatim.
/// </summary>
public sealed record Payload
{
    [JsonPropertyName("customerExternalId")]
    public required string CustomerExternalId { get; init; }

    [JsonPropertyName("amount")]
    public required decimal Amount { get; init; }

    [JsonPropertyName("description")]
    public required string Description { get; init; }
}

/// <summary>Identifiers generated by Service A that Service B needs.</summary>
public sealed record ServiceAIds
{
    [JsonPropertyName("customerId")]
    public required string CustomerId { get; init; }

    [JsonPropertyName("operationId")]
    public required string OperationId { get; init; }

    [JsonPropertyName("internalRequestId")]
    public required string InternalRequestId { get; init; }
}

/// <summary>
/// Raw request as captured by the Proxy and published to <c>proxy.requests</c>.
/// Kafka key = <see cref="CorrelationId"/>.
/// </summary>
public sealed record RequestReceived
{
    [JsonPropertyName("correlationId")]
    public required string CorrelationId { get; init; }

    [JsonPropertyName("requestId")]
    public required string RequestId { get; init; }

    [JsonPropertyName("createdAtUtc")]
    public required DateTimeOffset CreatedAtUtc { get; init; }

    [JsonPropertyName("payload")]
    public required Payload Payload { get; init; }
}

/// <summary>
/// Emitted by Service A to <c>service-a.completed</c> once processing finishes.
/// Carries the same <see cref="CorrelationId"/> as the originating request.
/// </summary>
public sealed record ServiceACompleted
{
    [JsonPropertyName("correlationId")]
    public required string CorrelationId { get; init; }

    [JsonPropertyName("completedAtUtc")]
    public required DateTimeOffset CompletedAtUtc { get; init; }

    [JsonPropertyName("serviceAIds")]
    public required ServiceAIds ServiceAIds { get; init; }
}

/// <summary>
/// Enriched command the Enricher publishes to <c>service-b.ready</c> after joining a
/// <see cref="RequestReceived"/> with its <see cref="ServiceACompleted"/>. The only
/// message Service B ever consumes.
/// </summary>
public sealed record ServiceBCommand
{
    [JsonPropertyName("correlationId")]
    public required string CorrelationId { get; init; }

    [JsonPropertyName("createdAtUtc")]
    public required DateTimeOffset CreatedAtUtc { get; init; }

    [JsonPropertyName("originalPayload")]
    public required Payload OriginalPayload { get; init; }

    [JsonPropertyName("serviceAIds")]
    public required ServiceAIds ServiceAIds { get; init; }
}
